### ISSUE TITLE
Add localization to Spanish

### ISSUE THREAD

**Issue by jhonatasrm** [jhonatasrm/tab-refresh#10]
**Actual behavior**
The strings in [messages.json](https://github.com/jhonatasrm/tab-refresh/blob/master/src/_locales/es/messages.json) are partially translated and needs a review in Spanish.

**Expected behavior**
The strings in [messages.json](https://github.com/jhonatasrm/tab-refresh/blob/master/src/_locales/es/messages.json) needs to be localized/reviewed to Spanish.

**Comment by natastro** [comment]
Happy to work on the Spanish translations if needed!

**Comment by jhonatasrm** [comment]
Awesome! Thank you for the help! 🙂
