### ISSUE TITLE
TAB refreshed while I was using it

### ISSUE THREAD

**Issue by murko69** [jhonatasrm/tab-refresh#5]
In the settings "Do not refresh the tab if you are using" I have that set to ON (enabled) and I thought that would make the TAB NOT refresh as long as the tab was active?

It worked fine during the night, keeping me logged in to a page that more or less requires activite every 5 minutes or so, otherwise I get logged out. During the night the tab was inactive cause I had another one in front.

Twenty minutes ago I started using the tab I'm using this addon for (it was set for 3 minutes). I went to a forum page and started wrighting a post. I got pretty far in 3 minutes when all of a sudden the tab refreshed and my text was gone.

Did I miunderstand the settings or wasn't this supposed to happen?
If you need further info from me just ask.
Thanks

**Comment by jhonatasrm** [comment]
>In the settings "Do not refresh the tab if you are using" I have that set to ON (enabled) and I thought that would make the TAB NOT refresh as long as the tab was active?

yes, it was supposed to work that way.

> Twenty minutes ago I started using the tab I'm using this addon for (it was set for 3 minutes). I went to a forum page and started wrighting a post. I got pretty far in 3 minutes when all of a sudden the tab refreshed and my text was gone.

omg.. I'm so sorry about that.

> Did I miunderstand the settings or wasn't this supposed to happen?

That was not supposed to happen, I'm so sorry about this... I will see here and work on a fix and I will let you know when finished. 

Thank you very much for your feedback.

**Comment by murko69** [comment]
Actually I found another bug (or might be the reason why I had issues in the first place)
If I click the icon and activate the addon I can see a "3" inside the arrow indicating it will update in 3 minutes. If I change my mind I click the icon again and it goes back to being just an arrow, indicating it will not refresh.
As soon as I click on a link or refresh the page manually, the refresh-icon is activated again on the tab.

This should not happen I guess. If I click on the icon one time, it should be enabled. If I click it a second time it should be disabled and stay disabled until I enable it again. Not just because the tab itself is updated

**Comment by jhonatasrm** [comment]
>This should not happen I guess. If I click on the icon one time, it should be enabled. If I click it a second time it should be disabled and stay disabled until I enable it again. Not just because the tab itself is updated

I will take a look at that too this week.

**Comment by jhonatasrm** [comment]
Hello! 

I released an update to the Add-on (v1.4.3) to fix that issue...Please if possible checks if the issue still happens.

🙂

**Comment by murko69** [comment]
Thanks. I will check in a few hours when I'm back home

**Comment by murko69** [comment]
So far so good. It stays disabled on second click even if page is refreshed manually and as of yet I have not seen an automated refresh of the tab (when enabled) when I'm using it!

Great fix!

**Comment by jhonatasrm** [comment]
Awesome! Any problem or suggestion, please let me know... Thank you again for open that issue.

🙂
