### ISSUE TITLE
install tab-refresh manually.

### ISSUE THREAD

**Issue by rickmoua** [jhonatasrm/tab-refresh#7]
I have a machine that has no Internet access.  I download the file "tab-refresh-master" and unzipped it.  Is it possible to put this add-on to firefox manually.  I'm using the latest firefox.

**Comment by jhonatasrm** [comment]
Yes, sure...

1- In the Firefox address bar enter ```about:debugging```
2- Click ```Load Temporary Add-on```, a dialog window opens
3- Select in the unziped file the manifest.json and the add-on icon will appear in your toolbar

🙂

**Comment by rickmoua** [comment]
After I close the browser and open a new one, it is no longer there.

**Comment by rickmoua** [comment]
Also, is there a way to get rid of the minimized and the close button on the firefox?

**Comment by jhonatasrm** [comment]
> After I close the browser and open a new one, it is no longer there.

Yes, it is temporary... You can open the add-on page ``about:addons`` and click at the gear, select the option to install from a file, but for that, u will need to generate the extension in *.xpi, [this article](https://hacks.mozilla.org/2015/09/lets_write_a_webextension/) can be useful.

:)
